example_4.settings:
  type: config_object
  label: 'Example settings.'
  mapping:
    example_thing:
      type: text
      label: 'Just an example.'
    other_things:
      type: text
      label: 'Just another example.'